export const USER_EMAIL = "USER_EMAIL"
export const ADD_HEAD = "ADD_HEAD"
export const ADD_DESCRIPT = "ADD_DESCRIPT"
export const ADD_VIDEO = "ADD_VIDEO"
export const ADD_PHOTO = "ADD_PHOTO"
export const ADD_COORDINATES = "ADD_COORDINATES"